my_dbt:
  outputs:
    dev:
      catalog: null
      host: '{{ env_var("DATABRICKS_HOST") }}'
      http_path: '{{ env_var("DATABRICKS_HTTP_PATH") }}'
      schema: default
      threads: 1
      token: '{{ env_var("DATABRICKS_TOKEN") }}'
      type: databricks
  target: dev
